mutation pwdLogin($password: String!, $username: String!) {
  pwdLogin(password: $password, username: $username)
}

mutation startBot($startBotId: String, $name: String) {
  startBot(id: $startBotId, name: $name) {
    scanQrcode
    id
  }
}

mutation SaveAutoStartConfig($input: AutoReplyConfigInput!) {
  saveAutoStartConfig(input: $input) {
    name
    content
    description
    priority
    triggerType
    triggerRate
    triggerPeriod
    createdAt
    updatedAt
    botId
    id
  }
}
