query myself {
  myself {
    id
    mobilePhoneNumber
    username
    avatar
    mobilePhoneVerified
    nickname
    createdAt
    updatedAt
    roles
  }
}

query botStatus($botId: String!) {
  bot(id: $botId) {
    botStatus
  }
}

query bot($botId: String!, $botContactsRefresh: Boolean, $botRoomsRefresh: Boolean) {
  bot(id: $botId) {
    id
    name
    scanQrcode
    botStatus
    botContacts(refresh: $botContactsRefresh) {
      id
      name
      gender
      alias
      address
      type
      botId
    }
    botRooms(refresh: $botRoomsRefresh) {
      id
      topic
      announce
      alias
    }
  }
}
